# include server-generated schema and client-side schemas
# see: https://www.graphql-code-generator.com/docs/integrations/apollo-local-state
schema:
  - ./src/app/generated/server.model.graphql
  - ./src/app/graphql/schemas/**/*.graphql

# collect client-side component& service queries, mutations, fragments
documents: ./src/**/*.gql
extensions:
  codegen:
    config:
      # replace generated files
      overwrite: true
      serviceProvidedInRoot: true
    generates:
      # generate apollo-angular client service
      # see: https://www.graphql-code-generator.com/plugins/typescript/typescript-apollo-angular
      ./src/app/generated/civic.apollo.ts:
        plugins:
          - typescript
          - typescript-operations
          - typescript-apollo-angular
          - add:
              content: /* eslint-disable */
        config:
          apolloClientVersion: 3
          nonOptionalTypename: true
          futureProofUnions: false
          futureProofEnums: false
          maybeValue: T | undefined
      ./src/app/generated/civic.possible-types.ts:
        plugins:
          - fragment-matcher
        config:
          apolloClientVersion: 3
          useExplicitTyping: false
      ./src/app/generated/civic.apollo-helpers.ts:
        plugins:
          - typescript-apollo-client-helpers
        config:
          useTypeImports: true
