fragment SuggestRevisionSetActivityDetail on SuggestRevisionSetActivity {
  parsedNote {
    ...parsedCommentFragment
  }
  revisions {
    ...RevisionActivityDetail
  }
  ...ActivityFeedItemBase
  ...ActivityFeedItemEvents
}