fragment SuggestRevisionSetActivityDetail on SuggestRevisionSetActivity {
  parsedNote {
    ...parsedCommentFragment
  }
  revisions {
    id
    name
    currentValue
    suggestedValue
    fieldName
    link
    createdAt
    linkoutData {
      ...revisionLinkoutData
    }
  }
  ...ActivityFeedItemBase
  ...ActivityFeedItemEvents
}
