query MolecularProfileSummary($mpId: Int!) {
  molecularProfile(id: $mpId) {
    ...MolecularProfileSummaryFields
  }
}

fragment MolecularProfileSummaryFields on MolecularProfile {
  id
  name
  description
  molecularProfileAliases
  molecularProfileScore
  sources {
    id
    citation
    link
    sourceType
    deprecated
  }
  variants {
    ...VariantMolecularProfileCardFields
  }
  parsedName {
    ...MolecularProfileParsedName
  }
  complexMolecularProfileCreationActivity {
    createdAt
    user {
      id
      displayName
      role
      profileImagePath(size: 32)
    }
  }
  variantDeprecationActivity{
    createdAt
    user {
      id
      displayName
      role
      profileImagePath(size: 32)
    }
  }
  complexMolecularProfileDeprecationActivity{
    createdAt
    user {
      id
      displayName
      role
      profileImagePath(size: 32)
    }
    parsedNote {
      ...parsedCommentFragment
    }
  }
}

fragment MolecularProfileParsedName on MolecularProfileSegment {
  __typename
  ... on MolecularProfileTextSegment {
    text
  }
  ... on Feature {
    id
    name
    link
    deprecated
    flagged
  }
  ... on Variant {
    id
    name
    link
    deprecated
    flagged
  }
}

fragment VariantMolecularProfileCardFields on VariantInterface {
  id
  name
  link
  deprecated
  flagged
  feature {
    id
    name
    link
    deprecated
    flagged
  }
  molecularProfiles(first: 3) {
    totalCount
    nodes {
      id
      link
      name
      deprecated
      flagged
    }
  }
  ... on GeneVariant {
    ... GeneVariantSummaryFields
  }
  ... on FactorVariant {
    ... FactorVariantSummaryFields
  }
  ... on FusionVariant {
    ... FusionVariantSummaryFields
  }
  variantAliases
  variantTypes {
    id
    link
    soid
    name
  }
}
