query RevisionPopover($revisionId: Int!) {
  revision(id: $revisionId) {
    ...revisionPopover
  }
}

fragment revisionPopover on Revision {
  id
  name
  link
  status
  creationActivity {
    user {
      id
      displayName
      role
    }
    parsedNote {
      ...parsedCommentFragment
    }
  }
  subject {
    id
    link
    name
    ... on VariantInterface {
      deprecated
      flagged
      feature {
        id
        name
        link
        deprecated
        flagged
      }
    }
    ... on Feature {
      deprecated
      flagged
    }
    ... on Assertion {
      flagged
    }
    ... on EvidenceItem {
      flagged
    }
    ... on VariantGroup {
      flagged
    }
  }
  createdAt
  linkoutData {
    name
  }
}
