query RevisionPopover($revisionId: Int!) {
  revision(id: $revisionId) {
    ...revisionPopover
  }
}

fragment revisionPopover on Revision {
  id
  name
  link
  status
  creationActivity {
    user {
      id
      displayName
      role
    }
    parsedNote {
      __typename
      ... on CommentTagSegment {
        entityId
        displayName
        tagType
        status
        deprecated
        link
        revisionSetId
        __typename
      }
      ... on CommentTextSegment {
        text
      }
      ... on User {
        id
        displayName
        role
      }
    }
  }
  subject {
    id
    link
    name
  }
  createdAt
  linkoutData {
    name
  }
}
