query UserLeaderboards(
  $window: TimeWindow
  $first: Int
  $last: Int
  $before: String
  $after: String
) {
  userCommentsLeaderboard(
    first: $first
    last: $last
    before: $before
    after: $after
    window: $window
  ) {
    pageInfo {
      endCursor
      hasNextPage
      hasPreviousPage
      startCursor
    }
    edges {
      cursor
      node {
        ...LeaderboardUserFields
      }
    }
    nodes {
      ...LeaderboardUserFields
    }
  }
  userModerationLeaderboard(
    first: $first
    last: $last
    before: $before
    after: $after
    window: $window
  ) {
    pageInfo {
      endCursor
      hasNextPage
      hasPreviousPage
      startCursor
    }
    edges {
      cursor
      node {
        ...LeaderboardUserFields
      }
    }
    nodes {
      ...LeaderboardUserFields
    }
  }
  userRevisionsLeaderboard(
    first: $first
    last: $last
    before: $before
    after: $after
    window: $window
  ) {
    pageInfo {
      endCursor
      hasNextPage
      hasPreviousPage
      startCursor
    }
    edges {
      cursor
      node {
        ...LeaderboardUserFields
      }
    }
    nodes {
      ...LeaderboardUserFields
    }
  }
  userSubmissionsLeaderboard(
    first: $first
    last: $last
    before: $before
    after: $after
    window: $window
  ) {
    pageInfo {
      endCursor
      hasNextPage
      hasPreviousPage
      startCursor
    }
    edges {
      cursor
      node {
        ...LeaderboardUserFields
      }
    }
    nodes {
      ...LeaderboardUserFields
    }
  }
}

fragment LeaderboardUserFields on LeaderboardUser {
  id
  name
  displayName
  actionCount
  role
  rank
  profileImagePath(size: 32)
}
