fragment SuggestSourceActivityDetail on SuggestSourceActivity {
  parsedNote {
    ...parsedCommentFragment
  }
  sourceSuggestion {
    id
    status
    source {
      id
      name
      link
      deprecated
    }
    molecularProfile {
      id
      name
      link
      deprecated
    }
    disease {
      id
      name
      link
      deprecated
    }
  }
  ...ActivityFeedItemBase
  ...ActivityFeedItemEvents
}
