fragment FlagEntityActivityDetail on FlagEntityActivity {
  ...ActivityFeedItemBase
  ...ActivityFeedItemEvents
  parsedNote {
    ...parsedCommentFragment
  }
  flag {
    id
    link
    name
  }
}
