# query ActivityFeedCount(
#   #$subject: SubscribableQueryInput
#   $first: Int
#   $last: Int
#   $before: String
#   $after: String
#   $userId: Int
#   #$organizationId: Int
#   #$eventType: EventAction
#   #$includeAutomatedEvents: Boolean
#   #$mode: EventFeedMode
# ) {
#   activities(
#     #subject: $subject
#     first: $first
#     last: $last
#     before: $before
#     after: $after
#     userId: $userId
#     #organizationId: $organizationId
#     #eventType: $eventType
#     #mode: $mode
#     #includeAutomatedEvents: $includeAutomatedEvents
#   ) {
#     unfilteredCount
#   }
# }

query ActivityFeed(
  #$subject: SubscribableQueryInput
  $first: Int
  $last: Int
  $before: String
  $after: String
  $userId: [Int!]
  #$organizationId: Int
  #$eventType: EventAction
  #$mode: EventFeedMode
  #$includeAutomatedEvents: Boolean = true
  #$showFilters: Boolean!
) {
  activities(
    #subject: $subject
    first: $first
    last: $last
    before: $before
    after: $after
    userId: $userId
    #organizationId: $organizationId
    #eventType: $eventType
    #includeAutomatedEvents: $includeAutomatedEvents
    #mode: $mode
  ) {
    ...activityFeed
  }
}
fragment activityFeed on ActivityInterfaceConnection {
  pageInfo {
    startCursor
    endCursor
    hasNextPage
    hasPreviousPage
  }
  #eventTypes @include(if: $showFilters)
  #unfilteredCount
  #uniqueParticipants @include(if: $showFilters) {
  #  id
  #  displayName
  #  role
  #  profileImagePath(size: 32)
  #}
  #participatingOrganizations @include(if: $showFilters) {
  #  id
  #  name
  #  profileImagePath(size: 32)
  #}
  edges {
    cursor
    node {
      ...activityFeedNode
    }
  }
}

fragment activityFeedNode on ActivityInterface {
  id
  verbiage
  createdAt
  organization {
    id
    name
    profileImagePath(size: 32)
  }
  user {
    id
    username
    displayName
    role
    profileImagePath(size: 32)
  }
  subject {
    name
    id
    link
    ... on Source {
      citation
      sourceType
    }
    ... on EvidenceItem {
      status
    }
    ... on Assertion {
      status
    }
    ... on Revision {
      revisionSetId
    }
    ... on VariantInterface {
      deprecated
      feature {
        id
        name
        link
        deprecated
      }
    }
    ... on MolecularProfile {
      deprecated
    }
    ... on Feature {
      deprecated
    }
    __typename
  }
  ... on FlagEntityActivity {
    flag {
      id
      name
      link
    }
  }
}
