query ActivityFeed(
  $subject: [SubscribableQueryInput!]
  $first: Int
  $last: Int
  $before: String
  $after: String
  $organizationId: [Int!]
  $userId: [Int!]
  $activityType: [ActivityTypeInput!]
  $subjectType: [ActivitySubjectInput!]
  $mode: EventFeedMode
  $showFilters: Boolean!
  $requestDetails: Boolean!
) {
  activities(
    subject: $subject
    first: $first
    last: $last
    before: $before
    after: $after
    userId: $userId
    organizationId: $organizationId
    activityType: $activityType
    subjectType: $subjectType
    mode: $mode
  ) {
    ...ActivitiesConnectionFields
  }
}

fragment ActivitiesConnectionFields on ActivityInterfaceConnection {
  pageInfo {
    startCursor
    endCursor
    hasNextPage
    hasPreviousPage
  }
  pageCount
  totalCount
  unfilteredCount
  activityTypes @include(if: $showFilters)
  uniqueParticipants @include(if: $showFilters) {
    id
    displayName
    role
  }
  subjectTypes @include(if: $showFilters)
  participatingOrganizations @include(if: $showFilters) {
    id
    name
  }
  edges {
    cursor
    node {
      ...ActivityFeedItem
    }
  }
  nodes {
    ...ActivityFeedItem
  }
}

fragment ActivityFeedItemBase on ActivityInterface {
  id
  verbiage
  createdAt
  organization {
    id
    name
  }
  user {
    id
    displayName
    role
  }
  subject {
    id
    name
    link
  }
  note @include(if: $requestDetails)
}

fragment ActivityFeedItem on ActivityInterface {
  ...ActivityFeedItemBase
  ...CommentActivityDetails @include(if: $requestDetails)
  # subject @include(if: $requestDetails) {
  #   id
  #   name
  #   link
  #   ... on Source {
  #     citation
  #     sourceType
  #   }
  #   ... on EvidenceItem {
  #     status
  #   }
  #   ... on Assertion {
  #     status
  #   }
  #   ... on Revision {
  #     ...RevisionDetails
  #   }
  #   ... on RevisionSet {
  #     id
  #     link
  #     name
  #     revisions {
  #       ...RevisionDetails
  #     }
  #   }
  #   ... on Variant {
  #     deprecated
  #   }
  #   ... on MolecularProfile {
  #     deprecated
  #   }
  # }
  # parsedNote @include(if: $requestDetails) {
  #   ... on CommentBodySegment {
  #     ... on CommentTagSegment {
  #       entityId
  #       link
  #       tagType
  #     }
  #     ... on CommentTextSegment {
  #       text
  #     }
  #   }
  #   ... on User {
  #     id
  #     displayName
  #     role
  #   }
  # }
  # events @include(if: $requestDetails) {
  #   id
  #   createdAt
  #   action
  #   originatingObject {
  #     id
  #     name
  #     link
  #   }
  #   originatingUser {
  #     id
  #     displayName
  #   }
  # }
}

fragment RevisionDetails on Revision {
  id
  revisionSetId
  name
  fieldName
  suggestedValue
}

fragment CommentDetails on Comment {
  id
  link
  name
  comment
}
