query ActivityFeed(
  $subject: [SubscribableQueryInput!]
  $first: Int
  $last: Int
  $before: String
  $after: String
  $organizationId: [Int!]
  $userId: [Int!]
  $activityType: [ActivityTypeInput!]
  $subjectType: [ActivitySubjectInput!]
  $mode: EventFeedMode
  $showFilters: Boolean!
  $requestDetails: Boolean!
) {
  activities(
    subject: $subject
    first: $first
    last: $last
    before: $before
    after: $after
    userId: $userId
    organizationId: $organizationId
    activityType: $activityType
    subjectType: $subjectType
    mode: $mode
  ) {
    ...ActivitiesConnectionFields
  }
}

fragment ActivitiesConnectionFields on ActivityInterfaceConnection {
  pageInfo {
    startCursor
    endCursor
    hasNextPage
    hasPreviousPage
  }
  pageCount
  totalCount
  unfilteredCount
  activityTypes @include(if: $showFilters)
  uniqueParticipants @include(if: $showFilters) {
    id
    displayName
    role
  }
  subjectTypes @include(if: $showFilters)
  participatingOrganizations @include(if: $showFilters) {
    id
    name
  }
  edges {
    cursor
    node {
      ...ActivityFeedItem
    }
  }
  nodes {
    ...ActivityFeedItem
  }
}

fragment ActivityFeedItemBase on ActivityInterface {
  id
  verbiage
  createdAt
  organization {
    id
    name
  }
  user {
    id
    displayName
    role
  }
  subject {
    id
    name
    link
  }
  note @include(if: $requestDetails)
}

fragment ActivityFeedItem on ActivityInterface {
  ...ActivityFeedItemBase
  ...CommentActivityDetail @include(if: $requestDetails)
  ...FlagEntityActivityDetail @include(if: $requestDetails)
}
