query CitationTypeahead(
  $partialCitationId: String!
  $sourceType: SourceSource!
) {
  sourceTypeahead(citationId: $partialCitationId, sourceType: $sourceType) {
    ...SourceTypeaheadResult
  }
}

fragment SourceTypeaheadResult on Source {
  id
  name
  citation
  citationId
  sourceType
}
