// tools/generate-advanced-search-config.ts
import fs from 'fs'
import path from 'path'
import {
  buildClientSchema,
  GraphQLInputObjectType,
  GraphQLSchema,
} from 'graphql'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

export const endpointFilterTypes: Record<string, string> = {
  searchAssertions: 'AssertionSearchFilter',
  searchDiseases: 'DiseaseSearchFilter',
  searchEvidenceItems: 'EvidenceItemSearchFilter',
  searchFeatures: 'FeatureSearchFilter',
  searchMolecularProfiles: 'MolecularProfileSearchFilter',
  searchPhenotypes: 'PhenotypeSearchFilter',
  searchSources: 'SourceSearchFilter',
  searchTherapies: 'TherapySearchFilter',
  searchUsers: 'UserSearchFilter',
  searchVariants: 'VariantSearchFilter',
  searchVariantTypes: 'VariantTypeSearchFilter',
}

// path to the introspection JSON generated by graphql-codegen
const introspectionPath = path.resolve(
  __dirname,
  '../src/app/generated/client.schema.json'
)

// output TS module that your Angular app will import
const outputPath = path.resolve(
  __dirname,
  '../src/app/generated/adv-search-field-config.ts'
)

function loadSchema(): GraphQLSchema {
  const raw = fs.readFileSync(introspectionPath, 'utf8')
  const json = JSON.parse(raw)

  // codegen introspection may be `{ "__schema": ... }` or `{ "data": { "__schema": ... } }`
  const introspection = json.data ?? json
  return buildClientSchema(introspection)
}

function main() {
  const schema = loadSchema()
  const queryType = schema.getQueryType()

  if (!queryType) {
    throw new Error('Schema has no query type')
  }

  const fields = queryType.getFields()

  const configItems: string[] = []

  for (const [endpointName, filterTypeName] of Object.entries(
    endpointFilterTypes
  )) {
    const field = fields[endpointName]

    if (!field) {
      console.warn(`⚠️  Query field "${endpointName}" not found in schema`)
      continue
    }

    const gqlType = schema.getType(filterTypeName)

    if (!gqlType) {
      console.warn(`⚠️  Filter type "${filterTypeName}" not found in schema`)
      continue
    }

    if (!(gqlType instanceof GraphQLInputObjectType)) {
      console.warn(
        `⚠️  Type "${filterTypeName}" is not an input object (kind: ${gqlType.astNode?.kind ?? 'unknown'})`
      )
      continue
    }

    // tracer bullet: we just record the endpoint, filter type name and its fields.
    // later we’ll map these fields into real FormlyFieldConfig structures.
    const fieldNames = Object.keys(gqlType.getFields())

    configItems.push(
      `  ${JSON.stringify(endpointName)}: {
    endpoint: ${JSON.stringify(endpointName)},
    filterTypeName: ${JSON.stringify(filterTypeName)},
    filterFieldNames: ${JSON.stringify(fieldNames)},
  }`
    )
  }
  const fileContents = `/* auto-generated by tools/generate-advanced-search-config.ts */

// one config entry per search endpoint; tracer-bullet data only for now
export const ADVANCED_SEARCH_CONFIG: Record<any, any> = {
${configItems.join(',\n')},
} as const`

  fs.writeFileSync(outputPath, fileContents, 'utf8')
  // eslint-disable-next-line no-console
  console.log(
    `✅ Wrote advanced search config to ${path.relative(process.cwd(), outputPath)}`
  )
}

main()
