query AssertionsBrowse (
  $first: Int
  $last: Int
  $before: String
  $after: String
  $diseaseName: String
  $drugName: String
  $id: Int
  $summary: String
  $assertionDirection: EvidenceDirection
  $clinicalSignificance: EvidenceClinicalSignificance
  $assertionType: EvidenceType
  $variantId: Int,
  $molecularProfileId: Int,
  $evidenceId: Int,
  $molecularProfileName: String,
  $sortBy: AssertionSort
  $ampLevel: AmpLevel
  $organizationId: Int,
  $userId: Int,
  $phenotypeId: Int,
  $diseaseId: Int,
  $drugId: Int,
  $status: EvidenceStatusFilter,
) {
  assertions(
    first: $first
    last: $last
    before: $before
    after: $after
    diseaseName: $diseaseName
    drugName: $drugName
    id: $id
    summary: $summary
    assertionDirection: $assertionDirection
    clinicalSignificance: $clinicalSignificance
    assertionType: $assertionType
    variantId: $variantId,
    molecularProfileId: $molecularProfileId,
    sortBy: $sortBy,
    ampLevel: $ampLevel,
    molecularProfileName: $molecularProfileName,
    evidenceId: $evidenceId
    organizationId: $organizationId
    userId: $userId,
    phenotypeId: $phenotypeId
    drugId: $drugId
    diseaseId: $diseaseId,
    status: $status
  ) {
    totalCount
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
    edges {
      cursor
      node {
        ...AssertionBrowseFields
      }
    }
  }
}

fragment AssertionBrowseFields on Assertion {
  id
  name
  link
  molecularProfile {
    id
    name
    link
    parsedName {
      ...MolecularProfileParsedName
    }
  }
  disease {
    id
    name
    link
  }
  drugs {
    id
    name
    link
  }
  drugInteractionType
  summary
  assertionType
  assertionDirection
  clinicalSignificance
  ampLevel
  evidenceItemsCount
  status
}
