query AssertionsBrowse(
  $first: Int
  $last: Int
  $before: String
  $after: String
  $diseaseName: String
  $therapyName: String
  $id: Int
  $ids: [Int!]
  $summary: String
  $assertionDirection: EvidenceDirection
  $significance: EvidenceSignificance
  $assertionType: EvidenceType
  $variantId: Int
  $molecularProfileId: Int
  $evidenceId: Int
  $molecularProfileName: String
  $sortBy: AssertionSort
  $ampLevel: AmpLevel
  $organizationId: [Int!]
  $includeSubgroups: Boolean
  $userId: Int
  $phenotypeId: Int
  $diseaseId: Int
  $therapyId: Int
  $status: EvidenceStatusFilter
  $endorsingOrganizationIds: [Int!]
) {
  assertions(
    first: $first
    last: $last
    before: $before
    after: $after
    diseaseName: $diseaseName
    therapyName: $therapyName
    id: $id
    ids: $ids
    summary: $summary
    assertionDirection: $assertionDirection
    significance: $significance
    assertionType: $assertionType
    variantId: $variantId
    molecularProfileId: $molecularProfileId
    sortBy: $sortBy
    ampLevel: $ampLevel
    molecularProfileName: $molecularProfileName
    evidenceId: $evidenceId
    organization: { ids: $organizationId, includeSubgroups: $includeSubgroups }
    userId: $userId
    phenotypeId: $phenotypeId
    therapyId: $therapyId
    diseaseId: $diseaseId
    status: $status
    endorsingOrganizations: {
      ids: $endorsingOrganizationIds
      includeSubgroups: $includeSubgroups
    }
  ) {
    totalCount
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
    edges {
      cursor
      node {
        ...AssertionBrowseFields
      }
    }
  }
}

fragment AssertionBrowseFields on Assertion {
  id
  name
  link
  molecularProfile {
    id
    name
    link
    parsedName {
      ...MolecularProfileParsedName
    }
    deprecated
  }
  disease {
    id
    name
    link
    deprecated
  }
  therapies {
    id
    name
    link
    deprecated
  }
  therapyInteractionType
  summary
  assertionType
  assertionDirection
  significance
  ampLevel
  evidenceItemsCount
  status
  flagged
}
