query GeneComments(
  $geneId: Int!,
  $first: Int,
  $last: Int,
  $before: String,
  $after: String,
) {
  gene(id: $geneId) {
    id
    comments(
      first: $first,
      last: $last,
      before: $before,
      after: $after,
    ) {
      totalCount
      edges {
        node {
          id
          createdAt
          title
          comment
          commentor {
            id
            name
            profileImagePath(size: 32)
            organizations {
              id
              name
            }
            role
          }
        }
      }
    }
  }
}
