query Quicksearch($query: String!, $types: [SearchableEntities!]) {
  search(query: $query, types: $types) {
    ...QuicksearchResult
  }
}

fragment QuicksearchResult on SearchResult {
    id
    resultType
    name
    matchingText
}
