mutation CreateLinkedSource($input: CreateLinkedSourceInput!) {
  createLinkedSource(input: $input) {
    sourceLink {
      id
      reason
      note
      source {
        id
        name
      }
      linkedSource {
        id
        name
      }
    }
  }
}
