query BrowseVariantGroups(
  $first: Int
  $last: Int
  $before: String
  $after: String
  $sortBy: VariantGroupsSort
  $name: String
  $featureNames: String
  $variantNames: String
) {
  browseVariantGroups(
    first: $first
    last: $last
    before: $before
    after: $after
    sortBy: $sortBy
    name: $name
    featureNames: $featureNames
    variantNames: $variantNames
  ) {
    pageInfo {
      endCursor
      hasNextPage
      startCursor
      hasPreviousPage
    }
    totalCount
    filteredCount
    pageCount
    lastUpdated
    edges {
      cursor
      node {
        ...BrowseVariantGroupRowFields
      }
    }
  }
}

fragment BrowseVariantGroupRowFields on BrowseVariantGroup {
  id
  name
  link
  featureNames
  variantNames
  variantCount
  evidenceItemCount
}
