query DiseasesSummary($diseaseId: Int!) {
  disease(id: $diseaseId) {
    ...DiseasesSummaryFields
  }
}

fragment MyDiseaseInfoFields on MyDiseaseInfo {
    diseaseOntologyExactSynonyms
    diseaseOntologyRelatedSynonyms
    mesh
    icdo
    icd10
    ncit
    omim
    doDef
    doDefCitations
    mondoDef
    mondoId
}

fragment DiseasesSummaryFields on Disease {
  id
  name
  doid
  diseaseUrl
  displayName
  diseaseAliases
  link
  myDiseaseInfo {
    ...MyDiseaseInfoFields
  }
  deprecated
}
