query VariantSelect($name: String!, $geneId: Int) {
  variants(name: $name, first: 20, geneId: $geneId) {
    nodes {
      ... VariantTypeaheadFields
    }
  }
}

fragment VariantSelectFields on Variant {
  id
  name
}


