schema: ./model/*.graphql
documents: ./src/**/*.graphql
extensions:
  codegen:
    generates:
      ./src/generated/graphqlService.ts:
        plugins:
          - "typescript"
          - "typescript-operations"
          - "typescript-apollo-angular"
      ./schema/civic.schema.json:
        plugins:
          - "introspection"
