query ActivityFeedItem($id: Int!, $requestDetails: Boolean!) {
  activity(id: $id) {
    ...ActivityFeedItem
    note @include(if: $requestDetails)
  }
}

# ActivityFeedItemEvents is defined in ../activity-feed.fragments.gql to keep
# the generated-file import graph acyclic
