query ActivityFeedItem($id: Int!, $requestDetails: Boolean!) {
  activity(id: $id) {
    ...ActivityFeedItem
    note @include(if: $requestDetails)
  }
}

# ActivityFeedItemEvents lives in ../activity-feed.fragments.gql
