query FeatureDetail($featureId: Int!) {
  feature(id: $featureId) {
    ...FeatureDetailFields
  }
}

fragment FeatureDetailFields on FeatureInterface {
  id
  name
  ... on Gene {
    officialName
  }
  # flags(state: OPEN) {
  #   totalCount
  # }
  # revisions(status: NEW) {
  #   totalCount
  # }
  # comments {
  #   totalCount
  # }
}
