query FeatureDetail($featureId: Int!) {
  feature(id: $featureId) {
    ...FeatureDetailFields
  }
}

fragment FeatureDetailFields on Feature {
  id
  name
  fullName
  featureInstance {
    __typename
  }
  flags(state: OPEN) {
    totalCount
  }
   revisions(status: NEW) {
     totalCount
   }
   comments {
     totalCount
   }
}
