mutation SelectOrCreateFusion($organizationId: Int, $fivePrimeGeneId: Int, $fivePrimeRegulatoryFusionType: RegulatoryFusionType, $fivePrimePartnerStatus: FusionPartnerStatus!, $threePrimeGeneId: Int, $threePrimeRegulatoryFusionType: RegulatoryFusionType, $threePrimePartnerStatus: FusionPartnerStatus!) {
  createFusionFeature(input: {
    organizationId: $organizationId
    fivePrimeGene: {
      geneId: $fivePrimeGeneId,
      partnerStatus: $fivePrimePartnerStatus
      regulatoryFusionType: $fivePrimeRegulatoryFusionType
    },
    threePrimeGene: {
      geneId: $threePrimeGeneId,
      partnerStatus: $threePrimePartnerStatus,
      regulatoryFusionType: $threePrimeRegulatoryFusionType
    }

  }) {
    new
    feature {
      ...FeatureSummaryFields
    }
  }
}
