mutation SelectOrCreateFusion($organizationId: Int, $fivePrimeGeneId: Int, $fivePrimePartnerStatus: FusionPartnerStatus!, $threePrimeGeneId: Int, $threePrimePartnerStatus: FusionPartnerStatus! ) {
  createFusionFeature(input: {
    organizationId: $organizationId
    fivePrimeGene: {
      geneId: $fivePrimeGeneId,
      partnerStatus: $fivePrimePartnerStatus
    },
    threePrimeGene: {
      geneId: $threePrimeGeneId,
      partnerStatus: $threePrimePartnerStatus
    }

  }) {
    new
    feature {
      ...FeatureSummaryFields
    }
  }
}
