query CommentPopover($commentId: Int!) {
  comment(id: $commentId) {
    ...commentPopover
  }
}

fragment commentPopover on Comment {
  id
  name
  createdAt
  title
  comment
  commenter {
    id
    displayName
    role
  }
  commentable {
    id
    name
    link
    ...on Variant {
      deprecated
      feature {
        id
        name
        link
      }
    }
    __typename
  }
}
