query GeneDetail($geneId: Int!) {
  gene(id: $geneId) {
    id
    name
    officialName
    entrezId
    flags {
      totalCount
      filteredCount
    }
    revisions {
      totalCount
      filteredCount
    }
    comments {
      totalCount
      filteredCount
    }
    lifecycleActions {
      lastCommentedOn {
        createdAt
        id
        organization {
          id
          name
        }
        originatingUser {
          id
          name
        }
      }
      lastModified {
        createdAt
        id
        organization {
          id
          name
        }
        originatingUser {
          id
          name
        }
      }
      lastReviewed {
        createdAt
        id
        organization {
          id
          name
        }
        originatingUser {
          id
          name
        }
      }
    }
  }
}
