query GeneDetail($geneId: ID!) {
  gene(id: $geneId) {
    description
    entrezId
    aliases {
      name
    }
    id
    lifecycleActions {
      lastCommentedOn {
        createdAt
        id
        organization {
          id
          name
        }
        originatingUser {
          id
          name
        }
      }
      lastModified {
        createdAt
        id
        organization {
          id
          name
        }
        originatingUser {
          id
          name
        }
      }
      lastReviewed {
        createdAt
        id
        organization {
          id
          name
        }
        originatingUser {
          id
          name
        }
      }
    }
    name
    officialName
    sources {
      id
      citation
      sourceUrl
      sourceType
    }
    variants {
      edges {
        node {
          id
          name
          description
        }
      }
    }
    comments {
      id
      createdAt
      title
      comment
      commentor {
        id
        name
        organizations {
          id
          name
        }
        role
      }
    }
    revisions {
      id
      revisionsetId
      createdAt
      fieldName
      currentValue
      suggestedValue
      linkoutData {
        name
        diffValue {
          ... on ObjectFieldDiff {
            addedObjects {
              id
              displayName
              displayType
              entityType
            }
            removedObjects {
              id
              displayName
              displayType
              entityType
            }
            keptObjects {
              id
              displayName
              displayType
              entityType
            }
          }
          ... on ScalarField {
            value
          }
        }
      }
      revisor {
        id
        name
      }
      status
    }
    myGeneInfoDetails
  }
}
