query ActivityFeedItem($id: Int!, $requestDetails: Boolean!) {
  activity(id: $id) {
    ...ActivityFeedFields
  }
}

fragment ActivityFeedDetailFields on ActivityInterface {
  subject @include(if: $requestDetails) {
    id
    name
    link
    ... on Source {
      citation
      sourceType
    }
    ... on EvidenceItem {
      status
    }
    ... on Assertion {
      status
    }
    ... on Revision {
      revisionSetId
    }
    ... on Variant {
      deprecated
    }
    ... on MolecularProfile {
      deprecated
    }
  }
  parsedNote @include(if: $requestDetails) {
    ... on CommentTagSegment {
      entityId
      link
      tagType
    }
    ... on CommentTextSegment {
      text
    }
    ... on User {
      id
      displayName
    }
  }
  events @include(if: $requestDetails) {
    id
    createdAt
    action
    originatingObject {
      id
      name
      link
    }
    originatingUser {
      id
      displayName
    }
  }
}
