query ActivityFeedItem($id: Int!, $requestDetails: Boolean!) {
  activity(id: $id) {
    ...ActivityFeedFields
  }
}

fragment ActivityFeedDetailFields on ActivityInterface {
  subject @include(if: $requestDetails) {
    id
    name
    link
    ... on Source {
      citation
      sourceType
    }
    ... on EvidenceItem {
      status
    }
    ... on Assertion {
      status
    }
    ... on Revision {
      ...RevisionDetails
    }
    ... on RevisionSet {
      id
      link
      name
      revisions {
        ...RevisionDetails
      }
    }
    ... on Variant {
      deprecated
    }
    ... on MolecularProfile {
      deprecated
    }
  }
  parsedNote @include(if: $requestDetails) {
    ... on CommentBodySegment {
      ... on CommentTagSegment {
        entityId
        link
        tagType
      }
      ... on CommentTextSegment {
        text
      }
    }
    ... on User {
      id
      displayName
      role
    }
  }
  events @include(if: $requestDetails) {
    id
    createdAt
    action
    originatingObject {
      id
      name
      link
    }
    originatingUser {
      id
      displayName
    }
  }
}

fragment RevisionDetails on Revision {
  id
  revisionSetId
  name
  fieldName
  suggestedValue
}

fragment CommentDetails on Comment {
  id
  link
  name
  comment
}
