query GeneRevisions(
  $geneId: Int!,
  $first: Int,
  $last: Int,
  $before: String,
  $after: String,
) {
  gene(id: $geneId) {
    id
    revisions(
      first: $first,
      last: $last,
      before: $before,
      after: $after,
    ) {
      edges {
        node {
          id
          revisionsetId
          createdAt
          fieldName
          currentValue
          suggestedValue
          linkoutData {
            name
            diffValue {
              ... on ObjectFieldDiff {
                addedObjects {
                  id
                  displayName
                  displayType
                  entityType
                }
                removedObjects {
                  id
                  displayName
                  displayType
                  entityType
                }
                keptObjects {
                  id
                  displayName
                  displayType
                  entityType
                }
              }
              ... on ScalarField {
                value
              }
            }
          }
          revisor {
            id
            name
          }
          status
        }
      }
    }
  }
}
