query GeneRevisions(
  $geneId: Int!,
  $first: Int,
  $last: Int,
  $before: String,
  $after: String,
  $fieldName: String,
  $originatingUserId: Int
) {
  gene(id: $geneId) {
    id
    uniqueRevisors {
      username
      id
      profileImagePath(size: 32)
    }
    revisedFieldNames {
      name
      displayName
    }
    revisions(
      first: $first,
      last: $last,
      before: $before,
      after: $after,
      fieldName: $fieldName,
      originatingUserId: $originatingUserId
    ) {
      totalCount
      edges {
        node {
          id
          revisionsetId
          createdAt
          fieldName
          currentValue
          suggestedValue
          linkoutData {
            name
            diffValue {
              ... on ObjectFieldDiff {
                addedObjects {
                  id
                  displayName
                  displayType
                  entityType
                }
                removedObjects {
                  id
                  displayName
                  displayType
                  entityType
                }
                keptObjects {
                  id
                  displayName
                  displayType
                  entityType
                }
              }
              ... on ScalarField {
                value
              }
            }
          }
          revisor {
            id
            name
          }
          status
        }
      }
    }
  }
}
