query VariantTypeTypeahead($name: String!) {
  variantTypes(name: $name, first: 20) {
    edges {
      node {
        ...variantTypeTypeahead
      }
    }
  }
}

fragment variantTypeTypeahead on BrowseVariantType {
  id
  name
  soid
}
