query GetOriginalQuery($permalinkId: String!) {
  searchByPermalink(permalinkId: $permalinkId) {
    searchEndpoint
    originalQuery
    permalinkId
    formQuery @client
  }
}

query searchEvidenceItems(
  $query: EvidenceItemSearchFilter!
  $createPermalink: Boolean
) {
  searchEvidenceItems(query: $query, createPermalink: $createPermalink) {
    permalinkId
    resultIds
  }
}
query searchVariants($query: VariantSearchFilter!, $createPermalink: Boolean) {
  searchVariants(query: $query, createPermalink: $createPermalink) {
    permalinkId
    resultIds
  }
}

#query searchVariants($query: VariantSearchFilter!, $createPermalink: Boolean) {
#  searchVariants(query: $query, createPermalink: $createPermalink)
#}
