query VariantsMenu(
  $geneId: Int,
  $variantName: String,
  $variantTypeIds: [Int!],
  $first: Int,
  $last: Int,
  $before: String,
  $after: String,
  $sortBy: VariantMenuSort
  ) {
  variants(
    geneId: $geneId,
    name: $variantName,
    variantTypeIds: $variantTypeIds,
    first: $first,
    last: $last,
    before: $before,
    after: $after,
    sortBy: $sortBy
    ) {
    totalCount
    pageInfo {
      startCursor
      endCursor
      hasPreviousPage
      hasNextPage
    }
    edges {
      cursor
      node {
        ...menuVariant
      }
    }
  }
}

query VariantTypesForGene(
  $geneId: Int,
) {
  variantTypes(
    geneId: $geneId,
    first: 50
  ) {
    edges {
      node {
        ...menuVariantType
      }
    }
  }
}

fragment menuVariantType on BrowseVariantType {
  id
  name
  link
}

fragment menuVariant on Variant {
  id
  name
  link
  flagged
}
