query FeaturesSummary($featureId: Int!) {
  feature(id: $featureId) {
    ...FeatureSummaryFields
  }
}

fragment FeatureSummaryFields on Feature{
  id
  name
  fullName
  featureInstance {
    __typename
    ... on Gene {
      id
      description
      featureAliases
      name
      sources {
        id
        citation
        link
        sourceUrl
        displayType
        sourceType
      }
      entrezId
      myGeneInfoDetails
    }
  }
  # lastSubmittedRevisionEvent {
  #   originatingUser {
  #     id
  #     displayName
  #     role
  #     profileImagePath(size: 32)
  #   }
  # }
  # lastAcceptedRevisionEvent {
  #   originatingUser {
  #     id
  #     displayName
  #     role
  #     profileImagePath(size: 32)
  #   }
  # }
}
