query CoordinatesCard($variantId: Int!) {
  variant(id: $variantId) {
    ...CoordinatesCardFields
  }
}

fragment CoordinatesCardFields on VariantInterface {
  id
  name
  ... on GeneVariant {
    coordinates {
      ...CoordinateFields
    }
  }
}
