query CoordinatesCard($variantId: Int!) {
  variant(id: $variantId) {
    ...CoordinatesCardFields
  }
}

fragment CoordinatesCardFields on VariantInterface {
  id
  name
  ... on GeneVariant {
    referenceBuild
    ensemblVersion
    primaryCoordinates {
      representativeTranscript
      chromosome
      start
      stop
    }
    secondaryCoordinates {
      representativeTranscript
      chromosome
      start
      stop
    }
    referenceBases
    variantBases
  }
}
