query CoordinatesCard($variantId: Int!) {
  variant(id: $variantId) {
    ...CoordinatesCardFields
  }
}

fragment CoordinatesCardFields on VariantInterface {
  id
  name
  ... on GeneVariant {
    coordinates {
      ...CoordinateFields
    }
  }
  ... on FusionVariant {
    fivePrimeCoordinates {
      ...CoordinateFields
    }
    threePrimeCoordinates {
      ...CoordinateFields
    }
    fivePrimeStartExonCoordinates {
      ...ExonCoordinateFields
    }
    fivePrimeEndExonCoordinates {
      ...ExonCoordinateFields
    }
    threePrimeStartExonCoordinates {
      ...ExonCoordinateFields
    }
    threePrimeEndExonCoordinates {
      ...ExonCoordinateFields
    }
  }
}

fragment ExonCoordinateFields on ExonCoordinate {
  referenceBuild
  ensemblVersion
  chromosome
  representativeTranscript
  start
  stop
  exon
  exonOffset
  exonOffsetDirection
  ensemblId
  strand
  coordinateType
}
