import { TypePolicies } from '@apollo/client/cache'
import { relayStylePagination } from '@apollo/client/utilities'
import { CvcSourcePolicy } from './policies/source.policy'
import { CvcUserPolicy } from './policies/user.policy'
import { CvcActivityPolicy } from './policies/activity.policy'
import {
  StrictTypedTypePolicies,
  TypedTypePolicies,
} from '@app/generated/civic.apollo-helpers'

export const CvcTypePolicies: StrictTypedTypePolicies = {
  Gene: {
    fields: {
      comments: relayStylePagination(),
      revisions: relayStylePagination(),
      events: relayStylePagination(),
      variants: relayStylePagination(),
    },
  },
  Query: {
    fields: {
      activities: relayStylePagination([
        'subject',
        'organizationId',
        'userId',
        'activityType',
        'subjectType',
      ]),
      browseGenes: relayStylePagination([
        'entrezSymbol',
        'therapayName',
        'geneAlias',
        'diseaseName',
      ]),
      browseVariants: relayStylePagination([
        'variantName',
        'entrezSymbol',
        'diseaseName',
        'therapayName',
        'variantTypeId',
        'variantGroupId',
      ]),
      browseMolecularProfiles: relayStylePagination([
        'variantName',
        'entrezSymbol',
        'diseaseName',
        'therapyName',
        'molecularProfileScore',
        'molecularProfileAlias',
        'variantId',
      ]),
      browseVariantGroups: relayStylePagination([
        'name',
        'geneNames',
        'variantNames',
        'variantId',
      ]),
      browseSources: relayStylePagination([
        'name',
        'year',
        'sourceType',
        'citationId',
        'author',
        'journal',
        'clinicalTrialId',
        'id',
        'openAccess',
      ]),
      sourceSuggestions: relayStylePagination([
        'sourceType',
        'citationId',
        'sourceId',
        'molecularProfileName',
        'diseaseName',
        'comment',
        'submitter',
        'citation',
        'status',
        'submitterId',
      ]),
      browseDiseases: relayStylePagination(['name', 'doid', 'geneNames', 'id']),
      events: relayStylePagination([
        'subject',
        'organizationId',
        'originatingUserId',
        'eventType',
      ]),
      variants: relayStylePagination(['geneId', 'name']),
      molecularProfiles: relayStylePagination([
        'geneId',
        'name',
        'evidenceStatusFilter',
      ]),
      comments: relayStylePagination(['originatingUserId', 'subject']),
      evidenceItems: relayStylePagination([
        'diseaseName',
        'therapayName',
        'id',
        'description',
        'evidenceLevel',
        'evidenceDirection',
        'significance',
        'evidenceType',
        'evidenceRating',
        'variantOrigin',
        'variantId',
        'molecularProfileId',
        'assertionId',
        'organizationId',
        'userId',
        'phenotypeId',
        'diseaseId',
        'therapayId',
        'sourceId',
        'geneSymbol',
        'variantName',
        'status',
        'clinicalTrialId',
      ]),
      assertions: relayStylePagination([
        'diseaseName',
        'therapayName',
        'id',
        'name',
        'summary',
        'assertionDirection',
        'significance',
        'assertionType',
        'variantId',
        'molecularProfileId',
        'ampLevel',
        'geneName',
        'variantName',
        'evidenceId',
        'organizationId',
        'userId',
        'phenotypeId',
        'diseaseId',
        'therapayId',
        'status',
      ]),
      organizations: relayStylePagination(['name', 'id']),
      flags: relayStylePagination([
        'flaggable',
        'flaggingUserId',
        'resolvingUserId',
        'state',
      ]),
      phenotypes: relayStylePagination(['hpoId', 'name', 'id']),
      variantTypes: relayStylePagination(['soid', 'name', 'id']),
      therapies: relayStylePagination(['ncitId', 'name', 'id']),
      clinicalTrials: relayStylePagination(['nctId', 'name', 'id']),
      notifications: relayStylePagination([
        'notificationReason',
        'subscriptionId',
        'originatingObject',
        'eventType',
        'originatingUserId',
        'organizationId',
        'includeRead',
      ]),
      revisions: relayStylePagination([
        'subject',
        'status',
        'originatingUserId',
        'fieldName',
        'revisionsetId',
      ]),
      users: relayStylePagination(['userName', 'orgName', 'userRole']),
    },
  },
}
