query SourceTypeahead($partialCitationId: String!, $sourceType: SourceSource!) {
  sourceTypeahead(citationId: $partialCitationId, sourceType: $sourceType) {
    ...SourceTypeaheadResult
  }
}

fragment SourceTypeaheadFields on Source {
  id
  name
  citation
  citationId
  sourceType
}
