mutation SuggestVariantGroupRevision(
  $input: SuggestVariantGroupRevisionInput!
) {
  suggestVariantGroupRevision(input: $input) {
    clientMutationId
    variantGroup {
      id
    }
    results {
      newlyCreated
      id
      fieldName
    }
  }
}
