fragment variantTagFields on Variant {
  id
  name
}

fragment variantLinkableTagFields on Variant {
  id
  name
  link
}

fragment geneVariantTagFields on GeneVariant {
  id
  name
}

fragment geneVariantLinkableTagFields on GeneVariant {
  id
  name
  link
}

fragment factorVariantTagFields on FactorVariant {
  id
  name
}

fragment factorVariantLinkableTagFields on FactorVariant {
  id
  name
  link
}

fragment fusionVariantTagFields on FusionVariant {
  id
  name
}

fragment fusionVariantLinkableTagFields on FusionVariant {
  id
  name
  link
}

fragment clinicalTrialTagFields on ClinicalTrial {
  id
  name
}

fragment clinicalTrialLinkableTagFields on ClinicalTrial {
  id
  name
  link
}

fragment evidenceTagFields on EvidenceItem {
  id
  name
}

fragment evidenceLinkableTagFields on EvidenceItem {
  id
  name
  link
}

fragment assertionTagFields on Assertion {
  id
  name
}

fragment assertionLinkableTagFields on Assertion {
  id
  name
  link
}

fragment therapyTagFields on Therapy {
  id
  name
}

fragment therapyLinkableTagFields on Therapy {
  id
  name
  link
}

fragment diseaseTagFields on Disease {
  id
  name
}

fragment diseaseLinkableTagFields on Disease {
  id
  name
  link
}

fragment molecularProfileTagFields on MolecularProfile {
  id
  name
}

fragment molecularProfileLinkableTagFields on MolecularProfile {
  id
  name
  link
}

fragment phenotypeTagFields on Phenotype {
  id
  name
}

fragment phenotypeLinkableTagFields on Phenotype {
  id
  name
  link
}

fragment sourceTagFields on Source {
  id
  name
}

fragment sourceLinkableTagFields on Source {
  id
  name
  link
}

fragment variantTypeTagFields on VariantType {
  id
  name
}

fragment variantTypeLinkableTagFields on VariantType {
  id
  name
  link
}

fragment variantGroupTagFields on VariantGroup {
  id
  name
}

fragment variantGroupLinkableTagFields on VariantGroup {
  id
  name
  link
}

fragment clingenCodeTagFields on ClingenCode {
  id
  name
}

fragment acmgCodeTagFields on AcmgCode {
  id
  name
}
