
query SourceSummary(
  $sourceId: Int!
) {
  source(id: $sourceId) {
      ...SourceSummaryFields
  }
}

fragment SourceSummaryFields on Source {
  displayType
  title
  abstract
  publicationDate
  citationId
  fullJournalTitle
  pmcId
  authorString
  clinicalTrials {
    nctId
  }
} 