query BrowseGenes(
  $entrezSymbol: String,
  $drugName: String,
  $geneAlias: String,
  $diseaseName: String,
  $sortBy: GenesSort,
  $first: Int,
  $last: Int,
  $before: String,
  $after: String,
) {

  browseGenes(
    entrezSymbol: $entrezSymbol,
    drugName: $drugName,
    geneAlias: $geneAlias,
    diseaseName: $diseaseName,
    sortBy: $sortBy,
    first: $first,
    last: $last,
    before: $before,
    after: $after,
  ) {
    nodes {
      id
      entrezId
      name
      aliases {
        name
      }
      diseases {
        name
      }
      drugs {
        name
      }
      variantCount
      evidenceItemCount
      assertionCount
    }
    totalCount
    totalPageCount
    pageInfo {
      startCursor
      endCursor
      hasPreviousPage
      hasNextPage
    }
  }

}
