query DrugPopover($drugId: Int!) {
  drugs(id: $drugId) {
    edges {
      node {
        ...drugPopover
      }
    }
  }
}

fragment drugPopover on BrowseDrug {
  id
  name
  drugUrl
  ncitId
  assertionCount
  evidenceCount
}
