query AcmgCodeSelectTypeahead($code: String!) {
  acmgCodesTypeahead(queryTerm: $code) {
    ...SpecificationCriteriumSelectTypeaheadFields
  }
}

query AcmgCodeSelectTag($id: Int!) {
  acmgCode(id: $id) {
    ...SpecificationCriteriumSelectTypeaheadFields
  }
}

fragment SpecificationCriteriumSelectTypeaheadFields on SpecificationCriterium {
  id
  code: criterium
  name: criterium
  description
  tooltip: description
  exclusive
}