query SpecificationCriteriumSelectTypeahead($code: String!, $specification: Int) {
  specificationCriteriumTypeahead(queryTerm: $code, specificationId: $specification) {
    ...SpecificationCriteriumSelectTypeaheadFields
  }
}

query specificationCriteriumSelectTag($id: Int!) {
  specificationCriterium(id: $id) {
    ...SpecificationCriteriumSelectTypeaheadFields
  }
}

query ValidSpecifications($orgId: Int, $assertionType: AssertionType!) {
  specifications(organizationId: $orgId, assertionType: $assertionType) {
    ...SpecificationSelectFields
  }
}

fragment SpecificationSelectFields on Specification {
  id
  name
  version
}

fragment SpecificationCriteriumSelectTypeaheadFields on SpecificationCriterium {
  id
  code: criterium
  name: criterium
  description
  tooltip: description
  exclusive
}
