# Fetch only fields required for authorization, perms & tag display
query ViewerBase {
  viewer {
    id
    username
    role
    profileImagePath(size: 32)
    organizations {
      id
      name
      profileImagePath(size: 32)
    },
    mostRecentConflictOfInterestStatement {
      coiStatus
    }
    # fetch latest event to get most recent org
    events(first:1) {
      nodes {
        id
        createdAt
        organization {
          id
          name
          profileImagePath(size: 32)
        },
      }
    }
  }
}
