# Fetch only fields required for authorization, perms & tag display
query ViewerBase {
  viewer {
    ...viewerFields
  }
}

query ViewerNotificationCount {
  notifications {
    unreadCount
  }
}

fragment viewerFields on User {
    id
    username
    role
    displayName
    profileImagePath(size: 32)
    organizationsWithApprovalPrivileges {
      id
    }
    organizations {
      ...viewerOrganization
    }
    mostRecentConflictOfInterestStatement {
      coiStatus
    }
    mostRecentOrganizationId
}

fragment viewerOrganization on Organization {
    id
    name
    profileImagePath(size: 32)
}
