fragment RejectRevisionsActivityDetail on RejectRevisionsActivity {
  parsedNote {
    ...parsedCommentFragment
  }
  revisions {
    ...RevisionActivityDetail
  }

  ...ActivityFeedItemBase
  ...ActivityFeedItemEvents
}
