mutation SelectOrCreateRegion($organizationId: Int, $cytogeneticRegionId: Int!) {
  createRegionFeature(input: {
    organizationId: $organizationId
    cytogeneticRegionIds: [$cytogeneticRegionId]
  }) {
    new
    feature {
      ...FeatureSummaryFields
    }
  }
}
