query UserCard($userId: Int!) {
  user(userId: $userId) {
    ...cardUser
  }
}

fragment cardUser on User {
  id
  profileImagePath(size: 64)
  displayName
  bio
  organizations {
    id
    name
  }
}
