query TopGenesByVariants {
  topGenesByVariants {
    counts {
      name
      value: count
      link
    }
    total
    secondaryTotal
  }
}

query TopDiseasesByEvidence {
  topDiseasesByEvidence {
    total
    counts {
      name
      value: count
      link
    }
    secondaryTotal
  }
}

query EvidenceLevelCounts {
  evidenceLevelCounts {
    name
    value: count
  }
}

query EvidenceRatingCounts {
  evidenceRatingCounts {
    name
    value: count
  }
}

query EvidenceStatusCounts {
  evidenceStatusCounts {
    name
    value: count
  }
}

query AmpLevelCounts {
  ampCategoryCounts {
    total
    counts {
      name
      value: count
    }
  }
}

query EvidenceTypeCounts {
  evidenceTypeCounts {
    evidenceTypeCounts {
      counts {
        value: count
        name
      }
      total
    }
    clinicalSignificanceCounts {
      ...SubsetCounts
    }
    supportCounts {
      ...SupportCounts
    }
  }
}

fragment SubsetCounts on CountsAndTotalWithKey {
  key
  counts {
    counts {
      name
      value: count
    }
    total
  }
}

fragment SupportCounts on SeriesWithKey {
  key
  series {
    name: key
    series: counts {
      value: count
      name
    }
  }
}