query TopGenesByVariants {
  topGenesByVariants {
    counts {
      name
      count
      link
    }
    total
    secondaryTotal
  }
}

query EvidenceTypeCounts {
  evidenceTypeCounts {
    primaryCounts {
      counts {
        name
        count
      }
      total
    }
    subsetCounts {
      ...SubsetCounts
    }
  }
}

fragment SubsetCounts on CountsAndTotalWithKey {
  key
  counts {
    counts {
      name
      count
    }
    total
  }
}