query TopGenesByVariants {
  topGenesByVariants {
    counts {
      name
      count
      link
    }
    total
    secondaryTotal
  }
}

query EvidenceTypeCounts {
  evidenceTypeCounts {
    evidenceTypeCounts {
      counts {
        count
        name
      }
      total
    }
    clinicalSignificanceCounts {
      ...SubsetCounts
    }
    supportCounts {
      ...SubsetCounts
    }
    doesNotSupportCounts {
      ...SubsetCounts
    }
  }
}

fragment SubsetCounts on CountsAndTotalWithKey {
  key
  counts {
    counts {
      name
      count
    }
    total
  }
}