query ActivityFeedUpdates(
  $subject: [SubscribableQueryInput!]
  $organizationId: [Int!]
  $includeSubgroups: Boolean
  $userId: [Int!]
  $activityType: [ActivityTypeInput!]
  $subjectType: [ActivitySubjectInput!]
  $includeAutomatedEvents: Boolean
  $mode: EventFeedMode
  $occurredAfter: ISO8601DateTime
) {
  activities(
    subject: $subject
    userId: $userId
    includeAutomatedEvents: $includeAutomatedEvents
    organization: {ids: $organizationId, includeSubgroups: $includeSubgroups}
    activityType: $activityType
    subjectType: $subjectType
    mode: $mode
    occurredAfter: $occurredAfter
  ) {
    pageInfo {
      startCursor
      endCursor
      hasNextPage
      hasPreviousPage
    }
    pageCount
    totalCount
    unfilteredCount
  }
}
