inherit_gem:
  rubocop-rails-omakase: rubocop.yml

Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/RedundantReturn:
  Enabled: false
