source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.0'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails', branch: 'main'
gem 'rails', '~> 6.1.2', '>= 6.1.2.1'
# Use postgresql as the database for Active Record
gem 'pg', '~> 1.1'
# Use Puma as the app server
gem 'puma', '~> 5.0'
# Use SCSS for stylesheets
gem 'sass-rails', '>= 6'
# Transpile app-like JavaScript. Read more: https://github.com/rails/webpacker
gem 'webpacker', '~> 5.0'

gem 'rack-cors', '~> 1.1.1'

gem 'omniauth', '~> 2.0.2'
gem 'omniauth-github', '~> 2.0.0'
gem 'omniauth-google-oauth2', '~> 0.8.1'
gem 'omniauth-orcid', '~> 2.1.1'
gem 'omniauth-rails_csrf_protection', '~> 1.0.0'

gem 'graphql','~> 1.12.4'
gem 'graphql-batch', '~>0.4.3'
gem 'search_object_graphql', '0.3.1'

gem 'scenic', '~>1.5.4'

gem 'kaminari-activerecord', '~>  1.2.1'
gem 'graphql-pagination', '~> 1.1.2'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.4', require: false

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 4.1.0'
  # Display performance information such as SQL time and flame graphs for each request in your browser.
  # Can be configured to work on production as well see: https://github.com/MiniProfiler/rack-mini-profiler/blob/master/README.md
  gem 'rack-mini-profiler', '~> 2.0'
  gem 'listen', '~> 3.3'

  gem 'capistrano', '~> 3.10.0'
  gem 'capistrano-rails', '~> 1.4'
  gem 'capistrano-rbenv', '~> 2.0'
  gem 'capistrano-passenger', '~> 0.2.0'

  gem 'graphiql-rails', '~> 1.7.0'

  gem 'pry'
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '>= 3.26'
  gem 'simplecov'
  gem 'simplecov-lcov'
end
