query ValidSpecifications($assertionId: Int!) {
  validSpecifications(assertionId: $assertionId) {
    ...SpecificationDetailConfigFields
  }
}

query SpecificationFormConfig($specificationId: Int!) {
  specificationFormConfig(specificationId: $specificationId) {
    ...SpecificationConfigFields
  }
}

fragment SpecificationConfigFields on SpecificationFormConfig {
    specification {
      ...SpecificationDetailConfigFields
    }
    assessmentGroups {
      ...AssessmentGroupFormConfigFields
    }
}

fragment SpecificationDetailConfigFields on Specification {
  id
  name
  version
  specificationUrl
  sopPubmedId
  publishedOn
  evaluationMethod
}

fragment AssessmentGroupFormConfigFields on SpecificationAssessmentGroup {
  name
  description
  specificationCriterium {
    id
    criterium
    description
    modifiers
    mutuallyExclusiveCodes
    pointValue
  }
}

 mutation SubmitCriteriaEvaluations($input: SubmitCriteriaEvaluationsInput!) {
   submitCriteriaEvaluations(input: $input) {
     clientMutationId
   }
 }
