query GenesSummary($geneId: Int!) {
  gene(id: $geneId) {
    ...GeneSummaryFields
  }
}

fragment GeneSummaryFields on Gene {
  description
  entrezId
  featureAliases
  id
  name
  sources {
    id
    citation
    link
    sourceUrl
    displayType
    sourceType
  }
  myGeneInfoDetails
}
