fragment CommentActivityDetail on CommentActivity {
  comment {
    ...commentListNode
    commentable {
      id
      name
      link
    }
  }
  ...ActivityFeedItemBase
  ...ActivityFeedItemEvents
}
