fragment SubmitCriteriaEvaluationsActivityDetail on SubmitCriteriaEvaluationsActivity {
  ...ActivityFeedItemBase
  ...ActivityFeedItemEvents
  parsedNote {
    ...parsedCommentFragment
  }
  specification {
    ...SpecificationFields
  }
  specificationEvaluations {
    ...SpecificationEvaluationFields
  }
}
