query VariantTypeahead($name: String!, $geneId: Int) {
  variants(name: $name, geneId: $geneId, first: 20) {
    nodes {
      ... VariantTypeaheadFields
    }
  }
}

fragment VariantTypeaheadFields on Variant {
  id
  name
}
