query BrowseMolecularProfiles(
  $molecularProfileName: String
  $variantName: String
  $variantId: Int
  $featureName: String
  $diseaseName: String
  $therapyName: String
  $molecularProfileAlias: String
  $sortBy: MolecularProfilesSort
  $first: Int
  $last: Int
  $before: String
  $after: String
) {
  browseMolecularProfiles(
    molecularProfileName: $molecularProfileName
    variantName: $variantName
    variantId: $variantId
    featureName: $featureName
    diseaseName: $diseaseName
    therapyName: $therapyName
    molecularProfileAlias: $molecularProfileAlias
    sortBy: $sortBy
    first: $first
    last: $last
    before: $before
    after: $after
  ) {
    pageInfo {
      endCursor
      hasNextPage
      startCursor
      hasPreviousPage
    }
    edges {
      cursor
      node {
        ...BrowseMolecularProfilesFields
      }
    }
    lastUpdated
    filteredCount
    pageCount
  }
}

fragment BrowseMolecularProfilesFields on BrowseMolecularProfile {
  id
  name
  evidenceItemCount
  molecularProfileScore
  assertionCount
  variantCount
  aliases {
    name
  }
  variants {
    id
    name
    link
    matchText
    feature {
      id
      link
      name
    }
  }
  therapies {
    id
    name
    link
  }
  diseases {
    id
    name
    link
  }
  link
}
