fragment AcceptRevisionsActivityDetail on AcceptRevisionsActivity {
  revisions {
    id
    name
    currentValue
    suggestedValue
    fieldName
    link
    linkoutData {
      ...revisionLinkoutData
    }
  }
  supersededRevisions {
    id
    link
    name
    creationActivity {
      user {
        displayName
        profileImagePath(size: 32)
        id
        role
      }
    }
    fieldName
    createdAt
  }
  ...ActivityFeedItemBase
  ...ActivityFeedItemEvents
}
