
query OrganizationMembers(
  $organizationId: Int!
) {
  organization(id: $organizationId) {
    members {
      ...OrganizationMembersFields
    }
  }
}

fragment OrganizationMembersFields on User {
  id
  name
  displayName
  profileImagePath(size:36)
  role
  url
  areaOfExpertise
  orcid
  twitterHandle
  facebookProfile
  linkedinProfile
} 