query OrganizationMembers(
  $organizationId: [Int!]
  $first: Int
  $last: Int
  $before: String
  $after: String
) {
  browseUsers(
    organization: { ids: $organizationId }
    first: $first
    last: $last
    before: $before
    after: $after
  ) {
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
    edges {
      cursor
      node {
        ...OrganizationMembersFields
      }
    }
  }
}

fragment OrganizationMembersFields on BrowseUser {
  id
  name
  displayName
  username
  profileImagePath(size: 64)
  role
  url
  areaOfExpertise
  orcid
  twitterHandle
  facebookProfile
  linkedinProfile
  organizations {
    id
    name
    url
  }
}
