fragment DeprecateVariantActivityDetail on DeprecateVariantActivity {
  parsedNote {
    ...parsedCommentFragment
  }
  molecularProfiles {
    id
    name
    link
    deprecated
    flagged
  }
  ...ActivityFeedItemBase
  ...ActivityFeedItemEvents
}
