query VariantPopover($variantId: Int!) {
  variant(id: $variantId) {
    ...variantPopoverFields
  }
}

fragment variantPopoverFields on VariantInterface {
  id
  name
  variantAliases
  ... on GeneVariant {
    alleleRegistryId
  }
  feature {
    id
    name
    link
  }
  molecularProfiles {
    totalCount
  }
  revisions(status: NEW) {
    totalCount
  }
  comments {
    totalCount
  }
  flags(state: OPEN) {
    totalCount
  }
}
