query VariantGroupPopover($variantGroupId: Int!) {
  variantGroup(id: $variantGroupId) {
    ...variantGroupPopoverFields
  }
}

fragment variantGroupPopoverFields on VariantGroup {
  id
  name
  description
  revisions(status: NEW) {
    totalCount
  }
  comments {
    totalCount
  }
  flags(state: OPEN) {
    totalCount
  }
  variants {
    edges {
      node {
        id
        name
        link
        deprecated
        flagged
        feature {
          id
          name
          link
          deprecated
          flagged
        }
      }
    }
  }
  sources {
    id
    citation
    sourceType
    link
    deprecated
  }
}
