mutation EndorseAssertion($input: EndorseAssertionInput!) {
  endorseAssertion(input: $input) {
    assertion {
      ...AssertionSummaryFields
    }
  }
}

mutation RevokeEndorsement($input: RevokeEndorsementInput!) {
  revokeEndorsement(input: $input) {
    assertion {
      ...AssertionSummaryFields
    }
  }
}
