# collect & merge model types 
schema: ../client/src/app/generated/civic.model.graphql
# collect & merge client queries, mutations, fragments
documents: ../client/src/**/*.gql
extensions:
  codegen:
    config:
      overwrite: true
      # relative to generated civic.apollo.ts
      ngModule: ../app.module#AppModule
    generates:
      # generate apollo-angular client service
      ../client/src/app/generated/civic.apollo.ts:
        plugins:
          - typescript
          - typescript-operations
          - typescript-apollo-angular
          - fragment-matcher
          - add:
              content: /* eslint-disable */
