# schema: ./model/*.graphql
# documents: ../client/src/**/*.graphql
# extensions:
#   codegen:
#     generates:
#       ../client/src/generated/gqlService.ts:
#         plugins:
#           - typescript
#           - typescript-operations
#           - typescript-apollo-angular
#           - add:
#               content: /* eslint-disable */
#       ./generated/gql.schema.json:
#         plugins:
#           - introspection
