# collect & merge model types 
schema: ./model/*.graphql
# collect & merge client queries, mutations, fragments
documents: ../client/src/**/*.graphql
extensions:
  codegen:
    config:
      overwrite: true
      # relative to generated GqlService.ts
      ngModule: ../app.module#AppModule
    generates:
      # generate apollo-angular client service
      ../client/src/app/generated/GqlService.ts:
        plugins:
          - typescript
          - typescript-operations
          - typescript-apollo-angular
          - fragment-matcher
          - add:
              content: /* eslint-disable */
      # generate introspection schema
      ../client/src/app/generated/gql.schema.json:
        plugins:
          - introspection
