query OrgFilterSearch($name: String) {
  browseOrganizations(name: $name) {
    pageInfo {
      endCursor
      hasNextPage
      hasPreviousPage
      startCursor
    }
    edges {
      node {
        id
        name
      }
    }
  }
}
