fragment DeprecateComplexMolecularProfileActivityDetail on DeprecateComplexMolecularProfileActivity {
  parsedNote {
    ...parsedCommentFragment
  }
  ...ActivityFeedItemBase
  ...ActivityFeedItemEvents
}
