query CytogeneticRegionSelectTypeahead($queryTerm: String!) {
  cytogeneticRegionTypeahead(queryTerm: $queryTerm) {
    ...CytogeneticRegionSelectTypeaheadFields
  }
}

query CytogeneticRegionSelectTag($cytogeneticRegionId: Int!) {
  cytogeneticRegion(id: $cytogeneticRegionId) {
    ...CytogeneticRegionSelectTypeaheadFields
  }
}

fragment CytogeneticRegionSelectTypeaheadFields on CytogeneticRegion {
  id
  name
}
