query ClingenCodeSelectTypeahead($code: String!) {
  clingenCodesTypeahead(queryTerm: $code) {
    ...SpecificationCriteriumSelectTypeaheadFields
  }
}

query ClingenCodeSelectTag($id: Int!) {
  clingenCode(id: $id) {
    ...SpecificationCriteriumSelectTypeaheadFields
  }
}