query VariantGroupsSummary($variantGroupId: Int!) {
  variantGroup(id: $variantGroupId) {
    ...VariantGroupSummaryFields
  }
}

fragment VariantGroupSummaryFields on VariantGroup {
  id
  name
  description
  # sources {
  #   id
  #   citation
  #   sourceUrl
  #   displayType
  #   sourceType
  # }
  # variants {
  #   edges {
  #     node {
  #       id
  #       name
  #       description
  #     }
  #   }
  # }
}
