query Revisions(
  $subject: ModeratedInput
  $first: Int
  $last: Int
  $before: String
  $after: String
  $fieldName: String
  $originatingUserId: Int
  $resolvingUserId: Int
  $revisionSetId: Int
  $status: RevisionStatus
) {
  revisions(
    first: $first
    last: $last
    before: $before
    after: $after
    fieldName: $fieldName
    originatingUserId: $originatingUserId
    resolvingUserId: $resolvingUserId
    subject: $subject
    status: $status
    revisionSetId: $revisionSetId
  ) {
    totalCount
    unfilteredCountForSubject
    uniqueRevisors {
      username
      id
      profileImagePath(size: 32)
    }
    uniqueResolvers {
      username
      id
      profileImagePath(size: 32)
    }
    revisedFieldNames {
      name
      displayName
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      endCursor
      startCursor
    }
    edges {
      node {
        ...revision
      }
    }
  }
}

fragment revision on Revision {
  id
  revisionSetId
  createdAt
  fieldName
  currentValue
  suggestedValue
  linkoutData {
    name
    diffValue {
      ... on ObjectFieldDiff {
        currentObjects {
          id
          displayName
          displayType
          entityType
          link
          deleted
          deprecated
          flagged
          feature {
            link
            id
            name
            deprecated
            flagged
          }
        }
        addedObjects {
          id
          displayName
          displayType
          entityType
          link
          deleted
          deprecated
          flagged
          feature {
            link
            id
            name
            deprecated
            flagged
          }
        }
        removedObjects {
          id
          displayName
          displayType
          entityType
          link
          deleted
          deprecated
          flagged
          feature {
            link
            id
            name
            deprecated
            flagged
          }
        }
        keptObjects {
          id
          displayName
          displayType
          entityType
          link
          deleted
          deprecated
          flagged
          feature {
            link
            id
            name
            deprecated
            flagged
          }
        }
        suggestedObjects {
          id
          displayName
          displayType
          entityType
          link
          deleted
          deprecated
          flagged
          feature {
            link
            id
            name
            deprecated
            flagged
          }
        }
      }
      ... on ScalarFieldDiff {
        left
        right
      }
    }
  }
  creationActivity {
    createdAt
    user {
      id
      displayName
      role
    }
    parsedNote {
      ...parsedCommentFragment
    }
    organization {
      id
      name
    }
  }
  resolutionActivity {
    createdAt
    user {
      id
      displayName
      role
    }
    parsedNote {
      ...parsedCommentFragment
    }
  }
  status
}
