query VariantGroupRevisions(
  $variantGroupId: Int!,
  $first: Int,
  $last: Int,
  $before: String,
  $after: String,
  $fieldName: String,
  $originatingUserId: Int
) {
  variantGroup(id: $variantGroupId) {
    id
    revisions(
      first: $first,
      last: $last,
      before: $before,
      after: $after,
      fieldName: $fieldName,
      originatingUserId: $originatingUserId
    ) {
      totalCount
      uniqueRevisors {
        username
        id
        profileImagePath(size: 32)
      }
      revisedFieldNames {
        name
        displayName
      }
      edges {
        node {
          id
          revisionsetId
          createdAt
          fieldName
          currentValue
          suggestedValue
          linkoutData {
            name
            diffValue {
              ... on ObjectFieldDiff {
                addedObjects {
                  id
                  displayName
                  displayType
                  entityType
                }
                removedObjects {
                  id
                  displayName
                  displayType
                  entityType
                }
                keptObjects {
                  id
                  displayName
                  displayType
                  entityType
                }
              }
              ... on ScalarFieldDiff {
                left
                right
              }
            }
          }
          revisor {
            id
            name
          }
          status
        }
      }
    }
  }
}
