query EventFeed (
    $subject: SubscribableInput
    $first: Int,
    $last: Int,
    $before: String,
    $after: String,
    $originatingUserId: Int,
    $organizationId: Int
){
events (
    subject: $subject,
    first: $first,
    last: $last,
    before: $before,
    after: $after,
    originatingUserId: $originatingUserId,
    organizationId: $organizationId
) { ...eventFeed }

}
fragment eventFeed on EventConnection {
    pageInfo {
        startCursor
        endCursor
        hasNextPage
        hasPreviousPage
    }
    eventTypes
    uniqueParticipants {
        id
        displayName
        profileImagePath(size: 32)
    }
    participatingOrganizations {
        id
        name
        profileImagePath(size: 32)
    }
    edges {
        cursor
        node {
            ...eventFeedNode
        }
    }
}

fragment eventFeedNode on Event {
    id
    action
    createdAt
    organization {
        id
        name
        profileImagePath(size: 32)
    }
    originatingUser {
        id
        username
        displayName
        profileImagePath(size: 32)
    }
    subject {
        name
        id
        __typename
    }
    originatingObject {
        id
        name
        ... on Revision {
            id
            revisor {
                id
                username
                profileImagePath(size: 32)
            }
            linkoutData {
                name
            }
            revisionsetId

        }
        ... on Comment {
            id
            comment
        }
        ... on Flag {
            id
            comments(first: 1) {
                nodes {
                    comment
                }
            }
        }
    }
}