query OrganizationsBrowse(
  $first: Int
  $last: Int
  $before: String
  $after: String
  $id: Int
  $orgName: String
  $sortBy: OrganizationSort
) {
  browseOrganizations(
    first: $first
    last: $last
    before: $before
    after: $after
    name: $orgName
    id: $id
    sortBy: $sortBy
  ) {
    totalCount
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
    edges {
      cursor
      node {
        ...OrganizationBrowseTableRowFields
      }
    }
  }
}

fragment OrganizationBrowseTableRowFields on BrowseOrganization {
  id
  name
  description
  url
  memberCount
  activityCount
  mostRecentActivityTimestamp
  childOrganizations {
    id
    name
  }
  # profileImagePath(size: 256) @include(if: $cardView)
  # orgStatsHash @include(if: $cardView) {
  #   comments
  #   revisions
  #   appliedRevisions
  #   submittedEvidenceItems
  #   acceptedEvidenceItems
  #   suggestedSources
  #   submittedAssertions
  #   acceptedAssertions
  # }
}
