query OrganizationsBrowse(
  $first: Int
  $last: Int
  $before: String
  $after: String
  $id: Int
  $orgName: String
  $sortBy: OrganizationSort
) {
  organizations(
    first: $first
    last: $last
    before: $before
    after: $after
    name: $orgName
    id: $id
    sortBy: $sortBy
  ) {
    totalCount
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
    edges {
      cursor
      node {
        ...OrganizationBrowseTableRowFields
      }
    }
  }
}

fragment OrganizationBrowseTableRowFields on Organization {
  id
  name
  description
  # profileImagePath(size: 256) @include(if: $cardView)
  url
  memberCount
  eventCount
  subGroups {
    name
    id
  }
  mostRecentActivityTimestamp
  # orgStatsHash @include(if: $cardView) {
  #   comments
  #   revisions
  #   appliedRevisions
  #   submittedEvidenceItems
  #   acceptedEvidenceItems
  #   suggestedSources
  #   submittedAssertions
  #   acceptedAssertions
  # }
}
