query MolecularProfileMenu(
  $geneId: Int
  $featureId: Int
  $mpName: String
  $first: Int
  $last: Int
  $before: String
  $after: String
  $evidenceStatusFilter: MolecularProfileDisplayFilter
) {
  molecularProfiles(
    geneId: $geneId
    featureId: $featureId
    name: $mpName
    evidenceStatusFilter: $evidenceStatusFilter
    first: $first
    last: $last
    before: $before
    after: $after
  ) {
    totalCount
    pageInfo {
      startCursor
      endCursor
      hasPreviousPage
      hasNextPage
    }
    edges {
      cursor
      node {
        ...menuMolecularProfile
      }
    }
  }
}

fragment menuMolecularProfile on MolecularProfile {
  id
  name
  link
  flagged
}
