mutation DeprecateVariant(
  $variantId: Int!
  $deprecationReason: VariantDeprecationReason!
  $comment: String!
  $organizationId: Int
) {
  deprecateVariant(
    input: {
      variantId: $variantId
      deprecationReason: $deprecationReason
      comment: $comment
      organizationId: $organizationId
    }
  ) {
    newlyDeprecatedMolecularProfiles {
      id
    }
    variant {
      id
      name
    }
  }
}

query MolecularProfilesForVariant($variantId: Int!) {
  molecularProfiles(variantId: $variantId, first: 50) {
    nodes {
      id
      name
      link
      evidenceCountsByStatus {
        submittedCount
        acceptedCount
      }
      deprecated
      flagged
    }
  }
}
