query SearchDiseases($query: DiseaseSearchFilter!, $createPermalink: Boolean) {
  searchDiseases(query: $query, createPermalink: $createPermalink) {
    resultIds
    permalinkId
    searchEndpoint
  }
}

query SearchByPermalink($permalinkId: String!) {
  searchByPermalink(permalinkId: $permalinkId) {
    resultIds
    searchEndpoint
  }
}
