query UsersBrowse(
  $first: Int
  $last: Int
  $before: String
  $after: String
  $userName: String
  $orgName: OrganizationFilter
  $userRole: UserRole
  $sortBy: UsersSort
) {
  users(
    first: $first
    last: $last
    before: $before
    after: $after
    name: $userName
    organization: $orgName
    role: $userRole
    sortBy: $sortBy
  ) {
    pageInfo {
      endCursor
      hasNextPage
      hasPreviousPage
      startCursor
    }
    totalCount
    edges {
      cursor
      node {
        ...UserBrowseTableRowFields
      }
    }
  }
}

fragment UserBrowseTableRowFields on BrowseUser {
  id
  name
  username
  organizations {
    id
    name
  }
  role
  evidenceCount
  revisionCount
  profileImagePath(size: 64)
  mostRecentActivityTimestamp
}
