query UsersBrowse(
  $first: Int
  $last: Int
  $before: String
  $after: String
  $name: String
  $organization: OrganizationFilter
  $role: UserRole
  $sortBy: UsersSort
) {
  browseUsers(
    first: $first
    last: $last
    before: $before
    after: $after
    name: $name
    organization: $organization
    role: $role
    sortBy: $sortBy
  ) {
    pageInfo {
      endCursor
      hasNextPage
      hasPreviousPage
      startCursor
    }
    totalCount
    edges {
      cursor
      node {
        ...UserBrowseTableRowFields
      }
    }
  }
}

fragment UserBrowseTableRowFields on BrowseUser {
  id
  name
  displayName
  username
  organizations {
    id
    name
  }
  role
  evidenceCount
  revisionCount
  profileImagePath(size: 64)
  mostRecentActivityTimestamp
}
