query BrowseDiseases(
  $first: Int
  $last: Int
  $before: String
  $after: String
  $sortBy: DiseasesSort
  $name: String
  $doid: String
  $featureName: String
) {
  browseDiseases(
    first: $first
    last: $last
    before: $before
    after: $after
    sortBy: $sortBy
    name: $name
    doid: $doid
    featureName: $featureName
  ) {
    pageInfo {
      endCursor
      hasNextPage
      hasPreviousPage
      startCursor
    }
    lastUpdated
    totalCount
    filteredCount
    pageCount
    edges {
      cursor
      node {
        ...BrowseDiseaseRowFields
      }
    }
  }
}

fragment BrowseDiseaseRowFields on BrowseDisease {
  id
  name
  doid
  diseaseUrl
  features {
    id
    name
    link
  }
  assertionCount
  evidenceItemCount
  variantCount
  featureCount
  link
  deprecated
}
