spectaql:

introspection:
  schemaFile: ./client/src/app/generated/civic.model.graphql

info:
  title: CiVIC 2 API Documentation
  description: Documentation for the CIViC GraphQL API
  termsOfService: https://www.example.com/terms
  contact:
    name: Development Team
    email: help@civicdb.org
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: https://example.com/graphql
    description: Production
    production: true
