query CommentList($geneId: Int!) {
  gene(id: $geneId) {
    comments {
      edges {
        node {
          id
          createdAt
          title
          comment
          commentor {
            id
            name
            profileImagePath(size: 32)
            organizations {
              id
              name
            }
            role
          }
        }
      }
    }
  }
}
