fragment commentList on CommentConnection {
  totalCount
  pageInfo {
    startCursor
    endCursor
    hasPreviousPage
    hasNextPage
  }
  edges {
    node {
      ...commentListNode
    }
  }
}

fragment commentListNode on Comment {
  id
  title
  comment
  createdAt
  commentor {
    id
    username
    name
    role
    profileImagePath(size: 32)
    organizations {
      id
      name
      profileImagePath(size: 32)
    }
  }
}
