query UserHoverCard($userId: Int!) {
  user(id: $userId) {
    ...hovercardUser
  }
}

fragment hovercardUser on User {
  id
  profileImagePath(size: 64)
  displayName
  bio
  role
  organizations {
    id
    name
  }
}