mutation QuickAddVariant($name: String!, $geneId: Int!) {
  addVariant(input: { name: $name, geneId: $geneId }) {
    ...QuickAddVariantFields
  }
}

fragment QuickAddVariantFields on AddVariantPayload {
  clientMutationId
  new
  variant {
    ...VariantSelectTypeaheadFields
  }
}
