mutation QuickAddVariant($name: String!, $geneId: Int!, $organizationId: Int) {
  createVariant(input: { name: $name, geneId: $geneId, organizationId: $organizationId }) {
    ...QuickAddVariantFields
  }
}

fragment QuickAddVariantFields on CreateVariantPayload {
  clientMutationId
  new
  variant {
    ...VariantSelectTypeaheadFields
  }
}
