mutation QuickAddVariant($name: String!, $featureId: Int!, $organizationId: Int) {
  createVariant(input: { name: $name, featureId: $featureId, organizationId: $organizationId }) {
    ...QuickAddVariantFields
  }
}

fragment QuickAddVariantFields on CreateVariantPayload {
  clientMutationId
  new
  variant {
    ...VariantSelectTypeaheadFields
  }
}
