name: Deploy CIViC

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      SSH_HOST:
        required: true
        type: string
      SSH_KEY:
        required: true
        type: string

jobs:
  deploy:
    name: Capistrano Deploy to Server
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key to Server
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: github-actions
          known_hosts: 'random-placeholder-value-replaced-by-keyscan-below'
          config: |
            host 35.87.115.86 
              IdentityFile ~/.ssh/github-actions
              IdentitiesOnly yes
              ForwardAgent yes
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }}

      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Deploy to production
        run: |
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/github-actions
          bundle exec cap ${{ inputs.environment }} deploy
