name: Build and deploy docs
on: 
  release:
    types: [published]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: release

      - name: Build docs
        run: |
          npm install spectaql
          npx spectaql --target-dir docs/build docs/config.yml

      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: docs/build
