fragment DeleteCommentActivityDetail on DeleteCommentActivity {
  comment {
    ...commentListNode
  }
  subject {
    id
    name
    link
  }
  ...ActivityFeedItemBase
  ...ActivityFeedItemEvents
}
