fragment DeleteCommentActivityDetail on DeleteCommentActivity {
  comment {
    deleted
    deletedAt
    ...commentListNode
  }
  subject {
    id
    name
    link
  }
  ...ActivityFeedItemBase
  ...ActivityFeedItemEvents
}
