query FlagPopover($flagId: Int!) {
  flag(id: $flagId) {
    ...flagPopover
  }
}

fragment flagPopover on Flag {
  id
  name
  state
  flaggingUser {
    id
    displayName
    role
  }
  flaggable {
    id
    link
    name
    ...on VariantInterface {
      deprecated
      feature {
        id
        name
        link
        deprecated
        flagged
      }
    }
    ... on Feature {
      deprecated
    }
    ... on EvidenceItem {
      status
    }
    ... on Assertion {
      status
    }
    flagged
  }
  createdAt
  openActivity {
    parsedNote {
      ...parsedCommentFragment
    }
  }
}
