query FlagPopover($flagId: Int!) {
  flag(id: $flagId) {
    ...flagPopover
  }
}

fragment flagPopover on Flag {
  id
  name
  state
  flaggingUser {
    id
    displayName
    role
  }
  flaggable {
    id
    link
    name
  }
  createdAt
  openActivity {
    note {
      __typename
      ... on CommentTagSegment {
        entityId
        displayName
        tagType
        status
        deprecated
        link
        revisionSetId
        __typename
      }
      ... on CommentTextSegment {
        text
      }
      ... on User {
        id
        displayName
        role
      }
    }
  }
}
